services:
  - type: web
    name: rasa-bot
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t rasa-bot .
    startCommand: docker run -p 5005:5005 rasa-bot
    port: 5005
